name: 台股每日趨勢與資金報告

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 1-5"

permissions:
  contents: write

jobs:
  你原本的工作名稱:
    runs-on: ubuntu-latest


  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests

      - name: Run the script
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python main.py
